[project]
name = "sns_autocalibration"
version = "0.0.1"
dependencies = [
    "modelskill==1.2.0",
    "optuna==4.2.1",
    "ipykernel",
    "jupyterlab==4.4.4",
    "mikeio==2.6.0",
    "torch==2.8.0",
    "cartopy==0.24.1",
    "plotly==6.2.0",
    "scikit-learn==1.7.0",
]

authors = [
  { name="Faro Schäfer", email="fsch@dhigroup.com" },
]
description = "A python repository that showcases an approach to automatically calibrate a DHI waterbench model."
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
